# Generated by Django 2.0.3 on 2018-10-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageUploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageinfo',
            old_name='ImageName',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='imageinfo',
            old_name='Url',
            new_name='url',
        ),
    ]
